name: Mobile Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/mobile/**'
      - 'tests/mobile/**'
      - 'wdio.conf.ts'
  pull_request:
    paths:
      - 'src/mobile/**'
      - 'tests/mobile/**'

jobs:
  android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29, 30]
        
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2
          appium &

      - name: Run Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: npm run test:mobile:android
        env:
          APPIUM_HOST: localhost
          APPIUM_PORT: 4723

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mobile-test-results-android-${{ matrix.api-level }}
          path: reports/mobile

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Appium
        run: |
          npm install -g appium
          appium driver install xcuitest
          appium &

      - name: Run iOS Tests
        run: npm run test:mobile:ios
        env:
          APPIUM_HOST: localhost
          APPIUM_PORT: 4723

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mobile-test-results-ios
          path: reports/mobile 